Repository MerginMaps/mobile, pull requests merged in 2021-01, with the labels that each got.

#1076 Android build to github actions
  .github/workflows/android.yml
  .travis.yml
  Input_keystore.keystore.enc
  app/ios/Info.plist
  app/version.pri
  qgsquick/from_qgis/CMakeLists.txt
  scripts/docker-build.sh
  scripts/upload-artifacts.sh
  scripts/uploader.py
  scripts/version.cmd
Labels: infrastructure, squash

#1091 Storage permission
  app/androidutils.cpp
  app/androidutils.h
  app/inpututils.cpp
  app/inpututils.h
  app/qml/MerginProjectPanel.qml
Labels: android, ui/ux

#1095 Faster Android scrolling in views
  app/qml/BrowseDataView.qml
  app/qml/InputStyle.qml
  app/qml/LayerList.qml
  app/qml/MerginProjectPanel.qml
Labels: FROZEN, android, ui/ux
