Repository MerginMaps/mobile, pull requests merged in 2021-02, with the labels that each got.

#1051 Support custom PROJ datum shifts
  .github/workflows/android.yml
  .github/workflows/autotests.yml
  .github/workflows/ios.yml
  .gitignore
  app/android.pri
  app/config.pri.default
  app/inputhelp.cpp
  app/inputhelp.h
  app/inputprojutils.cpp
  app/inputprojutils.h
  app/inpututils.cpp
  app/inpututils.h
  app/ios.pri
  app/ios/Info.plist
  app/linux.pri
  app/loader.cpp
  app/loader.h
  app/macx.pri
  app/main.cpp
  app/qml/main.qml
  app/sources.pri
  app/test/testutils.h
  app/version.pri
  app/win32.pri
  appveyor.yml
  qgsquick/CMakeLists.txt
  qgsquick/from_qgis/CMakeLists.txt
  qgsquick/from_qgis/attributes/qgsquickattributeformmodelbase.cpp
  qgsquick/from_qgis/attributes/qgsquickattributeformmodelbase.h
  qgsquick/from_qgis/plugin/CMakeLists.txt
  qgsquick/from_qgis/qgsquickmapsettings.h
  qgsquick/from_qgis/qgsquickpositionkit.cpp
  qgsquick/from_qgis/qgsquickutils.cpp
  scripts/ci/config.pri
  scripts/version.cmd
Labels: squash

#1113 add some explanatory text to help out users understand what mergin is
  app/qml/LoginForm.qml
Labels: enhancement, mergin

#1103 Project wizard
  app/fieldsmodel.cpp
  app/fieldsmodel.h
  app/inpututils.cpp
  app/inpututils.h
  app/localprojectsmanager.cpp
  app/localprojectsmanager.h
  app/main.cpp
  app/merginapi.cpp
  app/merginapi.h
  app/merginprojectmodel.cpp
  app/projectsmodel.cpp
  app/projectsmodel.h
  app/projectwizard.cpp
  app/projectwizard.h
  app/qml/FeatureToolbar.qml
  app/qml/InputStyle.qml
  app/qml/MerginProjectPanel.qml
  app/qml/ProjectWizardPage.qml
  app/qml/components/DelegateButton.qml
  app/qml/components/FieldRow.qml
  app/qml/components/Symbol.qml
  app/qml/qml.qrc
  app/sources.pri
Labels: squash

#1189 Unified feature form layout
  app/qml/FeaturePanel.qml
  app/qml/InputStyle.qml
  qgsquick/from_qgis/plugin/editor/qgsquickcheckbox.qml
  qgsquick/from_qgis/plugin/editor/qgsquickdatetime.qml
  qgsquick/from_qgis/plugin/editor/qgsquickeditorwidgetcombobox.qml
  qgsquick/from_qgis/plugin/editor/qgsquickexternalresource.qml
  qgsquick/from_qgis/plugin/editor/qgsquickrange.qml
  qgsquick/from_qgis/plugin/editor/qgsquicktextedit.qml
  qgsquick/from_qgis/plugin/editor/qgsquickvaluemap.qml
  qgsquick/from_qgis/plugin/editor/qgsquickvaluerelation.qml
  qgsquick/from_qgis/plugin/qgsquickfeatureform.qml
  qgsquick/from_qgis/plugin/qgsquickfeatureformstyling.qml
Labels: qgis
