Repository MerginMaps/mobile, pull requests merged in 2023-10, with the labels that each got.

#2810 fix crash ios gallery
  app/ios/iosinterface.mm
  app/ios/iosviewdelegate.h
  app/ios/iosviewdelegate.mm
Labels: ready-for-testing

#2820 Speed improvements of home page / sync preparation speed
  app/CMakeLists.txt
  app/projectsmodel.cpp
  app/qml/components/ProjectDelegateItem.qml
  app/test/inputtests.cpp
  app/test/testmerginapi.cpp
  app/test/testprojectchecksumcache.cpp
  app/test/testprojectchecksumcache.h
  core/CMakeLists.txt
  core/coreutils.cpp
  core/coreutils.h
  core/merginapi.cpp
  core/merginapi.h
  core/project.cpp
  core/project.h
  core/projectchecksumcache.cpp
  core/projectchecksumcache.h
  test/CMakeLists.txt
Labels: ready-for-testing

#2813 add missing CRS to project load errors
  app/activeproject.cpp
  app/activeproject.h
  app/qml/ProjectIssuesPanel.qml
  app/qml/main.qml
  app/test/testactiveproject.cpp
  app/test/testactiveproject.h
  test/test_data/project-with-missing-layer-and-invalid-crs/Survey_points_no_crs.gpkg
  test/test_data/project-with-missing-layer-and-invalid-crs/bad_layer.qgz
  test/test_data/project-with-missing-layer-and-invalid-crs/data.csv
Labels: ready-for-testing

#2836 Added new design for animated dialogs (Drawers) and Check items
  app/icons/CloseButton.svg
  app/icons/ReachedDataLimitImage.svg
  app/icons/UploadImage.svg
  app/icons/icons.qrc
  app/qmlV2/Style.js
  app/qmlV2/component/MMButton.qml
  app/qmlV2/component/MMDrawer.qml
  gallery/qml.qrc
  gallery/qml/Main.qml
  gallery/qml/pages/ChecksPage.qml
  gallery/qml/pages/DrawerPage.qml
Labels: FROZEN

#2845 Added test function testFormatDistanceInDistanceUnit
  app/inpututils.cpp
  app/inpututils.h
  app/test/testutilsfunctions.cpp
  app/test/testutilsfunctions.h
Labels: FROZEN

#2841 Fix image picker on desktops
  app/qml/CMakeLists.txt
  app/qml/ExternalResourceBundle.qml
  app/qml/PhotoPanel.qml
  app/qml/editor/inputexternalresource.qml
Labels: FROZEN

#2844 fix datetime picker 2
  app/qml/editor/inputdatetime.qml
Labels: bug in not released version

#2854 revert symbol size
  app/map/inputmapcanvasmap.cpp
Labels: bug in not released version, ready-for-testing

#2848 Highlight: use PathPolyline instead of PathMove/PathLine
  app/qml/map/Highlight.qml
Labels: ready-for-testing

#2860 fix photo in relation preview
  app/relationfeaturesmodel.cpp
Labels: ready-for-testing

#2876 fix digitizing polygon undo crash
  app/maptools/recordingmaptool.cpp
Labels: data corruption - sync failure - crash, ready-for-testing

#2849 Remove of purchasing backend & fix tests
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  CMakeLists.txt
  INSTALL.md
  app/CMakeLists.txt
  app/ios/iospurchasing.h
  app/ios/iospurchasing.mm
  app/main.cpp
  app/purchasing.cpp
  app/purchasing.h
  app/qml/AccountPage.qml
  app/qml/ProjectPanel.qml
  app/qml/WorkspaceAccountPage.qml
  app/test/inputtests.cpp
  app/test/inputtests.h
  app/test/testingpurchasingbackend.cpp
  app/test/testingpurchasingbackend.h
  app/test/testmerginapi.cpp
  app/test/testmerginapi.h
  app/test/testpurchasing.cpp
  app/test/testpurchasing.h
  app/test/testutils.cpp
  app/test/testutils.h
  cmake/FindAppleFrameworks.cmake
  cmake_templates/inputconfig.h.in
  core/CMakeLists.txt
  core/merginapi.h
  core/merginprojectmetadata.cpp
  core/merginprojectmetadata.h
  core/merginsubscriptioninfo.cpp
  core/merginsubscriptioninfo.h
  core/merginsubscriptiontype.cpp
  core/merginsubscriptiontype.h
  core/merginuserinfo.h
  test/CMakeLists.txt
Labels: squash, ready-for-testing

#2867 HTML, Text, Spacer "other form widgets" + "show label"
  app/attributes/attributecontroller.cpp
  app/attributes/attributecontroller.h
  app/attributes/attributedata.cpp
  app/attributes/attributedata.h
  app/attributes/attributeformmodel.cpp
  app/attributes/attributeformmodel.h
  app/inpututils.cpp
  app/qml/CMakeLists.txt
  app/qml/editor/AbstractEditor.qml
  app/qml/editor/inputrichtext.qml
  app/qml/editor/inputspacer.qml
  app/qml/form/FeatureForm.qml
  app/test/testattributecontroller.cpp
  app/test/testattributecontroller.h
  test/test_data/expressions/project.qgz
  test/test_data/expressions/survey.gpkg
Labels: enhancement, ready-for-testing

#2880 Photo crash on project switch
  app/attributes/attributecontroller.cpp
  app/inpututils.h
  app/qml/FormsStackManager.qml
  app/qml/form/FormWrapper.qml
Labels: data corruption - sync failure - crash, ready-for-testing

#2866 Default/virtual fields recalculation
  app/attributes/attributecontroller.cpp
  app/attributes/attributecontroller.h
  app/test/testattributecontroller.cpp
  app/test/testattributecontroller.h
  test/test_data/expressions/project.qgz
  test/test_data/expressions/survey.gpkg
Labels: bug, squash, ready-for-testing
